FROM registry.access.redhat.com/ubi8/openjdk-21:1.20

ENV LANGUAGE='en_US:en'
USER root
WORKDIR /workspace

COPY target/quarkus-app/lib/ /workspace/lib/
COPY target/quarkus-app/*.jar /workspace/
COPY target/quarkus-app/app/ /workspace/app/
COPY target/quarkus-app/quarkus/ /workspace/quarkus/

RUN chown -R 185:root /workspace && chmod -R g=u /workspace

EXPOSE 8080
USER 185
ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/workspace/quarkus-run.jar"

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]
