quarkus:
  banner:
    enabled: false
mock-fleet:
  mock-ops:
    namespace: ${MOCK_FLEET_NAMESPACE:mock-fleet}
    catalog-config-map-name: ${MOCK_FLEET_WIREMOCK_VERSION_CATALOG_CONFIG_MAP_NAME:mock-fleet-wiremock-version-catalog}
    baseline-config-map-name: ${MOCK_FLEET_WIREMOCK_BASELINE_CONFIG_MAP_NAME:mock-fleet-wiremock-config}
    user-config-map-name: ${MOCK_FLEET_WIREMOCK_USER_CONFIG_MAP_NAME:mock-fleet-wiremock-user-config}
    config-key: ${MOCK_FLEET_WIREMOCK_CONFIG_KEY:wiremock-options.yaml}
    registry-url: ${MOCK_FLEET_WIREMOCK_REGISTRY_URL:https://registry-1.docker.io}
    repository: ${MOCK_FLEET_WIREMOCK_REPOSITORY:wiremock/wiremock}
    image-repository: ${MOCK_FLEET_WIREMOCK_IMAGE_REPOSITORY:}
    default-version-constraint: ${MOCK_FLEET_WIREMOCK_DEFAULT_VERSION_CONSTRAINT:3.x}
    minor-lines: ${MOCK_FLEET_WIREMOCK_MINOR_LINES:5}
    page-size: ${MOCK_FLEET_WIREMOCK_PAGE_SIZE:100}
    registry-username: ${MOCK_FLEET_WIREMOCK_REGISTRY_USERNAME:}
    registry-password: ${MOCK_FLEET_WIREMOCK_REGISTRY_PASSWORD:}
