quarkus:
  log:
    category:
      "com.github.letsrokk":
        level: DEBUG
  kubernetes:
    image-pull-policy: if-not-present
    remote-debug:
      enabled: true
    env:
      vars:
        QUARKUS_LAUNCH_DEVMODE: "true"
        QUINOA_UI_DIR: /workspace/src/main/webui
        QUARKUS_PACKAGE_OUTPUT_DIRECTORY: /workspace/target
  quinoa:
    package-manager-install:
      node-version: 22.14.0
  package:
    jar:
      type: mutable-jar
  live-reload:
    password: mock-fleet-dev
