quarkus:
  quinoa:
    ui-dir: ${QUINOA_UI_DIR:${user.dir}/src/main/webui}
    ui-root-path: /__fleet
    build-dir: dist
    enable-spa-routing: true
    ignored-path-prefixes: /__fleet/api
  smallrye-health:
    root-path: /__fleet/health
  container-image:
    builder: docker
    registry: docker.io
    group: letsrokk
    name: mock-fleet
    build: true

mock-fleet:
  namespace: ${MOCK_FLEET_NAMESPACE:mock-fleet}
  inactivity-threshold: ${MOCK_FLEET_INACTIVITY_THRESHOLD:1M}
  pod-creation-timeout: ${MOCK_FLEET_POD_CREATION_TIMEOUT:1M}
  wiremock-image: wiremock/wiremock:3.9.2
  routing:
    mode: ${MOCK_FLEET_ROUTING_MODE:HOST}
    host: ${MOCK_FLEET_ROUTING_HOST:mock-fleet.localhost}
