{{- include "mock-fleet.validateSecurityBoundaries" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mock-fleet.apiFullname" . }}
  namespace: {{ include "mock-fleet.namespace" . }}
  labels:
    {{- include "mock-fleet.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  revisionHistoryLimit: 3
  replicas: {{ ternary 1 .Values.fleet.api.replicas .Values.fleet.api.dev.enabled }}
  strategy:
    type: {{ .Values.fleet.api.updateStrategy.type }}
    {{- if eq .Values.fleet.api.updateStrategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.fleet.api.updateStrategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.fleet.api.updateStrategy.rollingUpdate.maxSurge }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "mock-fleet.apiSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/wiremock-config: {{ include (print $.Template.BasePath "/wiremock-configmap.yaml") . | sha256sum }}
      labels:
        {{- include "mock-fleet.apiSelectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "mock-fleet.serviceAccountName" . }}
      automountServiceAccountToken: true
      terminationGracePeriodSeconds: {{ .Values.fleet.api.terminationGracePeriodSeconds }}
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        seccompProfile:
          type: RuntimeDefault
        {{- if .Values.storage.persistent }}
        fsGroup: 185
        fsGroupChangePolicy: OnRootMismatch
        {{- end }}
      containers:
        - name: api
          image: {{ printf "%s:%s" .Values.fleet.api.image.repository (.Values.fleet.api.image.tag | default .Chart.AppVersion) }}
          imagePullPolicy: {{ .Values.fleet.api.image.pullPolicy }}
          securityContext:
            runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MOCK_FLEET_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MOCK_FLEET_INACTIVITY_THRESHOLD
              value: {{ .Values.fleet.api.podInactivityThreshold | quote }}
            - name: MOCK_FLEET_POD_CREATION_TIMEOUT
              value: {{ .Values.fleet.api.podCreationTimeout | quote }}
            - name: MOCK_FLEET_MAX_ACTIVE_MOCKS
              value: {{ .Values.fleet.api.maxActiveMocks | quote }}
            - name: MOCK_FLEET_MAX_CONCURRENT_STARTS
              value: {{ .Values.fleet.api.maxConcurrentStarts | quote }}
            - name: MOCK_FLEET_QUEUED_START_CAPACITY
              value: {{ .Values.fleet.api.queuedStartCapacity | quote }}
            - name: QUARKUS_LOG_CONSOLE_JSON
              value: {{ .Values.fleet.api.logging.json | quote }}
            - name: QUARKUS_LOG_CATEGORY_COM_GITHUB_LETSROKK_LEVEL
              value: {{ .Values.fleet.api.logging.level | quote }}
            - name: MOCK_FLEET_WIREMOCK_POD_NAME_PREFIX
              value: {{ .Values.wiremock.podNamePrefix | quote }}
            - name: MOCK_FLEET_WIREMOCK_CONTAINER_NAME
              value: {{ .Values.wiremock.containerName | quote }}
            - name: MOCK_FLEET_WIREMOCK_IMAGE
              value: {{ .Values.wiremock.containerImage | quote }}
            - name: MOCK_FLEET_WIREMOCK_IMAGE_PULL_POLICY
              value: {{ .Values.wiremock.containerImagePullPolicy | quote }}
            - name: MOCK_FLEET_WIREMOCK_TERMINATION_GRACE_PERIOD_SECONDS
              value: {{ .Values.wiremock.terminationGracePeriodSeconds | quote }}
            {{- $wiremockServiceAccountName := include "mock-fleet.wiremockServiceAccountName" . }}
            {{- if $wiremockServiceAccountName }}
            - name: MOCK_FLEET_WIREMOCK_SERVICE_ACCOUNT_NAME
              value: {{ $wiremockServiceAccountName | quote }}
            {{- end }}
            - name: MOCK_FLEET_WIREMOCK_CONFIG_PATH
              value: /etc/mock-fleet/wiremock-options.yaml
            - name: MOCK_FLEET_WIREMOCK_USER_CONFIG_MAP_NAME
              value: {{ include "mock-fleet.wiremockUserConfigMapName" . | quote }}
            - name: MOCK_FLEET_WIREMOCK_CONFIG_KEY
              value: wiremock-options.yaml
            - name: MOCK_FLEET_WIREMOCK_RESOURCE_REQUEST_FLOOR_CPU
              value: {{ .Values.wiremock.resourcePolicy.requestFloor.cpu | quote }}
            - name: MOCK_FLEET_WIREMOCK_RESOURCE_REQUEST_FLOOR_MEMORY
              value: {{ .Values.wiremock.resourcePolicy.requestFloor.memory | quote }}
            - name: MOCK_FLEET_WIREMOCK_RESOURCE_LIMIT_CEILING_CPU
              value: {{ .Values.wiremock.resourcePolicy.limitCeiling.cpu | quote }}
            - name: MOCK_FLEET_WIREMOCK_RESOURCE_LIMIT_CEILING_MEMORY
              value: {{ .Values.wiremock.resourcePolicy.limitCeiling.memory | quote }}
            - name: MOCK_FLEET_PROXY_DEPLOYMENT_NAME
              value: {{ include "mock-fleet.proxyFullname" . | quote }}
            - name: MOCK_FLEET_PROXY_ROUTING_MODE
              value: {{ .Values.fleet.proxy.routing.mode | quote }}
            - name: MOCK_FLEET_PROXY_ROUTING_HOST
              value: {{ .Values.ingress.host | quote }}
            - name: MOCK_FLEET_MAPPINGS_MAX_DEPTH
              value: {{ .Values.fleet.api.mappings.maxDepth | quote }}
            - name: MOCK_FLEET_MAPPINGS_MAX_ENTRIES
              value: {{ .Values.fleet.api.mappings.maxEntries | quote }}
            - name: MOCK_FLEET_HAZELCAST_CLUSTER_NAME
              value: {{ .Values.hazelcast.clusterName | quote }}
            - name: MOCK_FLEET_HAZELCAST_SERVICE_DNS
              value: {{ printf "%s.%s.svc.cluster.local" (include "mock-fleet.apiHazelcastFullname" .) (include "mock-fleet.namespace" .) | quote }}
            - name: MOCK_FLEET_HAZELCAST_PORT
              value: {{ .Values.hazelcast.port | quote }}
            - name: MOCK_FLEET_HAZELCAST_BACKUP_COUNT
              value: {{ .Values.hazelcast.backupCount | quote }}
            - name: MOCK_FLEET_HAZELCAST_GRACEFUL_SHUTDOWN_MAX_WAIT_SECONDS
              value: {{ .Values.hazelcast.gracefulShutdownMaxWaitSeconds | quote }}
            - name: MOCK_FLEET_STORAGE_PERSISTENT
              value: {{ .Values.storage.persistent | quote }}
            - name: MOCK_FLEET_STORAGE_TYPE
              value: {{ .Values.storage.type | quote }}
            - name: MOCK_FLEET_STORAGE_PVC_NAME
              value: {{ printf "%s-pvc" (include "mock-fleet.fullname" .) | quote }}
            - name: MOCK_FLEET_STORAGE_MAPPINGS_PATH
              value: {{ .Values.storage.mappingsPath | quote }}
            - name: MOCK_FLEET_STORAGE_S3_PATH
              value: {{ .Values.storage.s3.path | quote }}
            {{- if .Values.fleet.api.dev.enabled }}
            - name: QUARKUS_LAUNCH_DEVMODE
              value: {{ .Values.fleet.api.dev.quarkusLaunchDevmode | quote }}
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.fleet.api.dev.javaToolOptions | quote }}
            {{- end }}
            - name: JAVA_OPTS
              value: {{ .Values.env.javaOpts | quote }}
            {{- if and (not .Values.fleet.api.dev.enabled) .Values.env.javaToolOptions }}
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.env.javaToolOptions | quote }}
            {{- end }}
            - name: user.dir
              value: {{ .Values.env.userDir | quote }}
          ports:
            - name: hazelcast
              containerPort: {{ .Values.hazelcast.port }}
              protocol: TCP
            - name: debug
              containerPort: {{ .Values.fleet.api.service.ports.targetDebug }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.fleet.api.service.ports.targetHttp }}
              protocol: TCP
          livenessProbe:
            failureThreshold: {{ .Values.fleet.api.probes.liveness.failureThreshold }}
            httpGet:
              path: {{ .Values.fleet.api.probes.liveness.path }}
              port: {{ .Values.fleet.api.service.ports.targetHttp }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.fleet.api.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.fleet.api.probes.liveness.periodSeconds }}
            successThreshold: {{ .Values.fleet.api.probes.liveness.successThreshold }}
            timeoutSeconds: {{ .Values.fleet.api.probes.liveness.timeoutSeconds }}
          readinessProbe:
            failureThreshold: {{ .Values.fleet.api.probes.readiness.failureThreshold }}
            httpGet:
              path: {{ .Values.fleet.api.probes.readiness.path }}
              port: {{ .Values.fleet.api.service.ports.targetHttp }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.fleet.api.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.fleet.api.probes.readiness.periodSeconds }}
            successThreshold: {{ .Values.fleet.api.probes.readiness.successThreshold }}
            timeoutSeconds: {{ .Values.fleet.api.probes.readiness.timeoutSeconds }}
          startupProbe:
            failureThreshold: {{ .Values.fleet.api.probes.startup.failureThreshold }}
            httpGet:
              path: {{ .Values.fleet.api.probes.startup.path }}
              port: {{ .Values.fleet.api.service.ports.targetHttp }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.fleet.api.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.fleet.api.probes.startup.periodSeconds }}
            successThreshold: {{ .Values.fleet.api.probes.startup.successThreshold }}
            timeoutSeconds: {{ .Values.fleet.api.probes.startup.timeoutSeconds }}
          resources:
            {{- toYaml .Values.fleet.api.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/mock-fleet
              name: wiremock-config
              readOnly: true
            {{- if .Values.storage.persistent }}
            - mountPath: {{ .Values.storage.mappingsPath | quote }}
              name: wiremock-mappings
            {{- end }}
      volumes:
        - name: wiremock-config
          configMap:
            name: {{ include "mock-fleet.wiremockConfigMapName" . }}
            optional: false
        {{- if .Values.storage.persistent }}
        - name: wiremock-mappings
          persistentVolumeClaim:
            claimName: {{ printf "%s-pvc" (include "mock-fleet.fullname" .) }}
        {{- end }}
