{{- if .Values.fleet.api.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mock-fleet.apiIngressNetworkPolicyName" . }}
  namespace: {{ include "mock-fleet.namespace" . }}
  labels:
    {{- include "mock-fleet.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-ingress
spec:
  podSelector:
    matchLabels:
      {{- include "mock-fleet.apiSelectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
    - from:
        - podSelector:
            matchLabels:
              {{- include "mock-fleet.apiSelectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.hazelcast.port }}
{{- end }}
