apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mock-fleet.hazelcastConfigMapName" . }}
  namespace: {{ include "mock-fleet.namespace" . }}
  labels:
    {{- include "mock-fleet.labels" . | nindent 4 }}
data:
  hazelcast-client.yaml: |
    hazelcast-client:
      cluster-name: {{ .Values.hazelcastClient.clusterName }}
      network:
        cluster-members:
          - {{ include "mock-fleet.hazelcastServiceName" . }}:5701
