{{- if .Values.fleet.mitmproxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mock-fleet.mitmproxyFullname" . }}
  namespace: {{ include "mock-fleet.namespace" . }}
  labels:
    {{- include "mock-fleet.labels" . | nindent 4 }}
    app.kubernetes.io/component: mitmproxy
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.fleet.mitmproxy.replicas }}
  selector:
    matchLabels:
      {{- include "mock-fleet.mitmproxySelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mock-fleet.mitmproxySelectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/mitmproxy-configmap.yaml") . | sha256sum }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: mitmproxy
          image: {{ printf "%s:%s" .Values.fleet.mitmproxy.image.repository (default .Chart.AppVersion .Values.fleet.mitmproxy.image.tag) | quote }}
          imagePullPolicy: {{ .Values.fleet.mitmproxy.image.pullPolicy }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          ports:
            - name: proxy
              containerPort: 8888
          startupProbe:
            tcpSocket:
              port: proxy
            periodSeconds: 2
            failureThreshold: 30
          readinessProbe:
            tcpSocket:
              port: proxy
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: proxy
            periodSeconds: 20
          resources:
            {{- toYaml .Values.fleet.mitmproxy.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/tinyproxy
              readOnly: true
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "mock-fleet.mitmproxyFullname" . }}
{{- end }}
