apiVersion: v1
kind: Service
metadata:
  name: {{ include "mock-fleet.fullname" . }}
  namespace: {{ include "mock-fleet.namespace" . }}
  labels:
    {{- include "mock-fleet.labels" . | nindent 4 }}
    app.kubernetes.io/component: fleet
spec:
  type: {{ .Values.fleet.service.type }}
  selector:
    {{- include "mock-fleet.fleetSelectorLabels" . | nindent 4 }}
  ports:
    - name: debug
      port: {{ .Values.fleet.service.ports.debug }}
      protocol: TCP
      targetPort: {{ .Values.fleet.service.ports.targetDebug }}
    - name: http
      port: {{ .Values.fleet.service.ports.http }}
      protocol: TCP
      targetPort: {{ .Values.fleet.service.ports.targetHttp }}
