{{- if .Values.fleet.tinyproxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mock-fleet.tinyproxyFullname" . }}
  namespace: {{ include "mock-fleet.namespace" . }}
  labels:
    {{- include "mock-fleet.labels" . | nindent 4 }}
    app.kubernetes.io/component: tinyproxy
data:
  tinyproxy.conf: |
    Port 8888
    Listen 0.0.0.0
    PidFile "/tmp/tinyproxy.pid"
    ConnectPort 443
    Filter "/etc/tinyproxy/allowed-hosts"
    FilterType ere
    FilterDefaultDeny Yes
    FilterCaseSensitive No
    {{- range $key, $value := .Values.fleet.tinyproxy.config }}
    {{ $key }} {{ $value }}
    {{- end }}
  allowed-hosts: |
    ^{{ if eq .Values.fleet.proxy.routing.mode "HOST" }}([a-z0-9]([a-z0-9-]*[a-z0-9])?\.)?{{ end }}{{ regexQuoteMeta (required "ingress.host is required for Tinyproxy" .Values.ingress.host) }}$
{{- end }}
