{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mock-fleet.wiremockMappingsPvcName" . }}
  namespace: {{ include "mock-fleet.namespace" . }}
  labels:
    {{- include "mock-fleet.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.storage.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
  storageClassName: {{ .Values.storage.storageClassName | quote }}
  {{- if .Values.storage.createPersistentVolume }}
  volumeName: {{ include "mock-fleet.wiremockMappingsPvName" . }}
  {{- end }}
{{- end }}
