{{- if and .Values.wiremock.versionUpdater.enabled .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mock-fleet.wiremockUpdaterRoleName" . }}
  namespace: {{ include "mock-fleet.namespace" . }}
  labels:
    {{- include "mock-fleet.labels" . | nindent 4 }}
    app.kubernetes.io/component: wiremock-updater
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - {{ include "mock-fleet.wiremockConfigMapName" . }}
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - {{ include "mock-fleet.wiremockUserConfigMapName" . }}
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - {{ include "mock-fleet.wiremockVersionCatalogConfigMapName" . }}
    verbs:
      - get
      - update
      - patch
{{- end }}
