apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mock-fleet.wiremockConfigMapName" . }}
  namespace: {{ include "mock-fleet.namespace" . }}
  labels:
    {{- include "mock-fleet.labels" . | nindent 4 }}
data:
  wiremock-options.yaml: |
    wiremock:
      default:
{{- toYaml .Values.fleet.api.wiremock.config.default | nindent 8 }}
      mocks:
{{- if .Values.fleet.api.wiremock.config.mocks }}
{{- toYaml .Values.fleet.api.wiremock.config.mocks | nindent 8 }}
{{- else }}
        []
{{- end }}
