---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-client-configmap
data:
  hazelcast-client.yaml: |
    hazelcast-client:
      cluster-name: dev
      network:
        cluster-members:
          - mock-fleet-hazelcast:5701
