ports:
  tinyproxy-http:
    port: 18080
    exposedPort: 8080
    expose:
      default: true
    protocol: TCP
  tinyproxy-https:
    port: 18433
    exposedPort: 8433
    expose:
      default: true
    protocol: TCP
