apiVersion: v2
name: mock-fleet
description: Deploy mock-fleet, a Quarkus service that routes requests to per-mock WireMock pods in Kubernetes
type: application
version: 1.0.0-SNAPSHOT
appVersion: "1.0.0-SNAPSHOT"
home: https://github.com/letsrokk/mock-fleet
sources:
  - https://github.com/letsrokk/mock-fleet
keywords:
  - mock-fleet
  - wiremock
  - quarkus
  - kubernetes
  - testing
dependencies:
  - name: hazelcast
    version: 5.10.1
    repository: https://hazelcast-charts.s3.amazonaws.com/
    alias: hazelcast
