ingress:
  enabled: true
  host: mock-fleet.minikube.localhost
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"

fleet:
  mcp:
    enabled: true
    allowedOrigins:
      - https://mock-fleet.minikube.localhost
  proxy:
    routing:
      mode: "PATH"
    replicas: 1
  api:
    replicas: 2

wiremock:
  config:
    default:
      options:
        - --verbose
        - --max-request-journal-entries 15

storage:
  persistent: true
  type: s3
  s3:
    storageClassName: seaweedfs-s3
    bucket: "default-bucket"
    mountOptions:
      - endpoint-url http://seaweedfs-s3.seaweedfs.svc.cluster.local:8333
      - force-path-style
      - allow-other
      - allow-delete
      - allow-overwrite
      - metadata-ttl minimal
      - region us-east-1
      - prefix mock-fleet/

#env:
#  javaToolOptions: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
