ingress:
  enabled: true
  host: mock-fleet.localhost
  className: nginx

fleet:
  routing:
    mode: PATH
  resources:
    requests:
      cpu: "1"
      memory: 4Gi
    limits:
      cpu: "2"
      memory: 4Gi

storage:
  persistent: true
  type: s3
  s3:
    storageClassName: seaweedfs-s3
    bucket: "default-bucket"
    mountOptions:
      - endpoint-url http://seaweedfs-s3.seaweedfs.svc.cluster.local:8333
      - force-path-style
      - region us-east-1
      - prefix mock-fleet/

env:
  quarkusLaunchDevmode: "true"
  javaToolOptions: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
