quarkus:
  log:
    console:
      json: ${QUARKUS_LOG_CONSOLE_JSON:false}
    category:
      "com.github.letsrokk":
        min-level: TRACE
        level: ${QUARKUS_LOG_CATEGORY_COM_GITHUB_LETSROKK_LEVEL:INFO}
  smallrye-health:
    root-path: /__fleet/proxy/health
  container-image:
    builder: docker
    registry: ghcr.io
    group: letsrokk/mock-fleet
    name: proxy
    additional-tags:
      - latest
    build: true

mock-fleet:
  api:
    base-url: ${MOCK_FLEET_API_BASE_URL:http://localhost:8081}
  routing:
    mode: ${MOCK_FLEET_ROUTING_MODE:HOST}
    host: ${MOCK_FLEET_ROUTING_HOST:mock-fleet.localhost}
