server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;

    location = /__fleet {
        return 302 /__fleet/;
    }

    location /__fleet/ {
        try_files $uri $uri/ /__fleet/index.html;
    }
}
