quarkus:
  log:
    console:
      json: ${QUARKUS_LOG_CONSOLE_JSON:false}
    category:
      "com.github.letsrokk":
        min-level: TRACE
        level: ${QUARKUS_LOG_CATEGORY_COM_GITHUB_LETSROKK_LEVEL:INFO}
  smallrye-health:
    root-path: /__fleet/api/health
  smallrye-openapi:
    path: /__fleet/api/openapi
  swagger-ui:
    always-include: true
    path: /__fleet/api/swagger-ui
  container-image:
    builder: docker
    registry: ghcr.io
    group: letsrokk/mock-fleet
    name: api
    additional-tags:
      - latest
    build: true

mock-fleet:
  namespace: ${MOCK_FLEET_NAMESPACE:mock-fleet}
  inactivity-threshold: ${MOCK_FLEET_INACTIVITY_THRESHOLD:1M}
  pod-creation-timeout: ${MOCK_FLEET_POD_CREATION_TIMEOUT:1M}
  wiremock-pod-name-prefix: ${MOCK_FLEET_WIREMOCK_POD_NAME_PREFIX:mock-fleet}
  wiremock-container-name: ${MOCK_FLEET_WIREMOCK_CONTAINER_NAME:wiremock}
  wiremock-image: ${MOCK_FLEET_WIREMOCK_IMAGE:wiremock/wiremock:latest}
  wiremock-image-pull-policy: ${MOCK_FLEET_WIREMOCK_IMAGE_PULL_POLICY:IfNotPresent}
  wiremock-service-account-name: ${MOCK_FLEET_WIREMOCK_SERVICE_ACCOUNT_NAME:}
  wiremock-config-path: ${MOCK_FLEET_WIREMOCK_CONFIG_PATH:}
  wiremock-user-config-map-name: ${MOCK_FLEET_WIREMOCK_USER_CONFIG_MAP_NAME:}
  wiremock-config-key: ${MOCK_FLEET_WIREMOCK_CONFIG_KEY:wiremock-options.yaml}
  proxy-deployment-name: ${MOCK_FLEET_PROXY_DEPLOYMENT_NAME:}
  hazelcast:
    cluster-name: ${MOCK_FLEET_HAZELCAST_CLUSTER_NAME:mock-fleet}
    service-dns: ${MOCK_FLEET_HAZELCAST_SERVICE_DNS:}
    port: ${MOCK_FLEET_HAZELCAST_PORT:5701}
    backup-count: ${MOCK_FLEET_HAZELCAST_BACKUP_COUNT:1}
    graceful-shutdown-max-wait-seconds: ${MOCK_FLEET_HAZELCAST_GRACEFUL_SHUTDOWN_MAX_WAIT_SECONDS:30}
  storage:
    persistent: ${MOCK_FLEET_STORAGE_PERSISTENT:false}
    type: ${MOCK_FLEET_STORAGE_TYPE:s3}
    pvc-name: ${MOCK_FLEET_STORAGE_PVC_NAME:mock-fleet-pvc}
    mappings-path: ${MOCK_FLEET_STORAGE_MAPPINGS_PATH:/workspace/mappings}
    s3:
      path: ${MOCK_FLEET_STORAGE_S3_PATH:/mock-fleet}
