quarkus:
  smallrye-health:
    root-path: /__fleet/api/health
  container-image:
    builder: docker
    registry: ghcr.io
    group: letsrokk
    name: mock-fleet-api
    additional-tags:
      - latest
    build: true

mock-fleet:
  namespace: ${MOCK_FLEET_NAMESPACE:mock-fleet}
  inactivity-threshold: ${MOCK_FLEET_INACTIVITY_THRESHOLD:1M}
  pod-creation-timeout: ${MOCK_FLEET_POD_CREATION_TIMEOUT:1M}
  wiremock-container-name: ${MOCK_FLEET_WIREMOCK_CONTAINER_NAME:wiremock}
  wiremock-image: ${MOCK_FLEET_WIREMOCK_IMAGE:wiremock/wiremock:latest}
  wiremock-image-pull-policy: ${MOCK_FLEET_WIREMOCK_IMAGE_PULL_POLICY:IfNotPresent}
  wiremock-config-path: ${MOCK_FLEET_WIREMOCK_CONFIG_PATH:}
  storage:
    persistent: ${MOCK_FLEET_STORAGE_PERSISTENT:false}
    type: ${MOCK_FLEET_STORAGE_TYPE:s3}
    pvc-name: ${MOCK_FLEET_STORAGE_PVC_NAME:mock-fleet-pvc}
    s3:
      path: ${MOCK_FLEET_STORAGE_S3_PATH:/mock-fleet}
